# Generated by Django 3.1.7 on 2021-04-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_hour', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200, null=True)),
                ('middleName', models.CharField(max_length=200, null=True)),
                ('lastName', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialityName', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patientReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('retry_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.doctor')),
                ('specialityID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.speciality')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_hour', models.DateTimeField(auto_now_add=True, null=True)),
                ('to_hour', models.DateTimeField(auto_now_add=True, null=True)),
                ('dayOfWeek', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='doctorReminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('retry_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialityName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.speciality'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('doctorID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctorName', to='clinicApp.appointments')),
                ('drugName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.drugs')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patientName', to='clinicApp.appointments')),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctorID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.doctor'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patientID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicApp.patient'),
        ),
    ]
