# Generated by Django 3.1.7 on 2021-04-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='doctorID',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='doctorID',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctorreminders',
            old_name='doctorID',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='doctorID',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='doctorspeciality',
            old_name='doctorID',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='doctorspeciality',
            old_name='specialityID',
            new_name='speciality',
        ),
        migrations.RenameField(
            model_name='patientreminders',
            old_name='patientID',
            new_name='patient',
        ),
    ]
