# Generated by Django 3.1.7 on 2021-04-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0003_auto_20210401_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firstNamee',
            new_name='firstName',
        ),
    ]
