# Generated by Django 3.1.7 on 2021-04-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0004_auto_20210401_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firstName',
            new_name='firstNamee',
        ),
    ]
