# Generated by Django 3.1.7 on 2021-04-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0005_auto_20210404_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='firstNamee',
            new_name='firstName',
        ),
    ]
