# Generated by Django 3.1.7 on 2021-04-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0007_auto_20210406_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
