# Generated by Django 3.1.7 on 2021-04-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0009_auto_20210408_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='re_password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='re_password',
        ),
    ]
