# Generated by Django 3.1.7 on 2021-04-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0010_auto_20210410_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
