# Generated by Django 3.1.7 on 2021-04-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0012_auto_20210413_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='dayOfWeek',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='from_hour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='to_hour',
            field=models.DateTimeField(null=True),
        ),
    ]
