# Generated by Django 3.1.7 on 2021-04-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0013_auto_20210419_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='dayOfWeek',
            new_name='day',
        ),
    ]
