# Generated by Django 3.1.7 on 2021-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0020_auto_20210429_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='from_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='to_hour',
            field=models.TimeField(null=True),
        ),
    ]
