# Generated by Django 3.1.7 on 2021-06-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0023_auto_20210605_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
