# Generated by Django 3.1.7 on 2021-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0024_auto_20210605_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='checkPrescription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
