# Generated by Django 3.1.7 on 2021-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0025_consultation_checkprescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='checkPrescription',
        ),
        migrations.AddField(
            model_name='appointments',
            name='checkPrescription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
