# Generated by Django 3.1.7 on 2021-06-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0027_auto_20210617_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user_id',
            new_name='user',
        ),
    ]
