# Generated by Django 3.1.7 on 2021-06-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicApp', '0029_auto_20210617_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
